In [1]:
import pandas as pd
df = pd.read_csv("CarPriceCombined.csv")
df

,title,make,model,trim,year,mileagekm,location,fueltype,registeredcity,color,enginecapacitycc,assembly,automatic,pricePKR
0,Toyota Corolla SE Saloon Automatic 2004,Toyota,Corolla,SE Saloon Automatic,2004,186000,Husaini chowk Ranger market hasil pur road,Petrol,Karachi,White,1600.0,local,Automatic,120000.0
1,Toyota Corolla Altis Grande CVT-i 1.8 2016,Toyota,Corolla,Altis Grande CVT-i 1.8,2016,159000,NaN,Petrol,Punjab,White,1800.0,local,Automatic,310000.0
2,Toyota Raize 2021,Toyota,Raize,,2021,1700,189-B PakArab Society Ferozpur Road15-A Moulan...,Petrol,Un-Registered,Red,1000.0,Imported,Automatic,439500.0
3,Honda Civic VTi Oriel 1.6 2004,Honda,Civic,VTi Oriel 1.6,2004,285000,NaN,Petrol,Sialkot,Grey,1600.0,local,NaN,137500.0
4,Toyota Vitz F 1.0 2018,Toyota,Vitz,F 1,2018,38000,Hockey Stadium Near Gourmet Bakery,Petrol,Lahore,White,1000.0,local,Automatic,275000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446,Mercedes Benz E-Class 1.8 E200 Kompressor 2003,Mercedes Benz,E-Class,1.8 E200 Kompressor,2003,"195,478","Ali Trade Centre, MM Alam Road, Block B1 Block...",Petrol,Lahore,Black,NaN,NaN,automatic,2500000.0
447,Toyota Corolla 1.3 XLI 2015,Toyota,Corolla,1.3 XLI,2015,"1,456","Shop No 1, 2 Sawera Residency Ground floor Plo...",Petrol,Karachi,Black,NaN,NaN,manual,2120000.0
448,Hyundai Santro 1.0 Club GV 2006,Hyundai,Santro,1.0 Club GV,2006,"190,110","Shop No 1, 2 Sawera Residency Ground floor Plo...",PetrolCompressedNaturalGas,Karachi,White,NaN,NaN,manual,780000.0
449,Toyota Corolla 1.3 GLI 2002,Toyota,Corolla,1.3 GLI,2002,"178,861","Plot, gate # 1, old bulb factory, near hamza q...",Petrol,Karachi,Green,NaN,NaN,manual,1350000.0
450,Honda Civic 1.8 i-VTEC Oriel CVT UG - FaceLift...,Honda,Civic,1.8 i-VTEC Oriel CVT UG - FaceLift,2019,"84,956","Shop No 1, 2 Sawera Residency Ground floor Plo...",Petrol,Karachi,Black,NaN,NaN,automatic,3950000.0

In [2]:
df.columns

Index(['title', 'make', 'model', 'trim ', 'year', 'mileagekm', 'location',
       'fueltype', 'registeredcity', 'color', 'enginecapacitycc', 'assembly',
       'automatic', 'pricePKR'],
      dtype='object')

In [3]:
df.isna().sum()

title                 0
make                  0
model                 0
trim                  0
year                  0
mileagekm             0
location            252
fueltype             48
registeredcity        0
color                 4
enginecapacitycc     90
assembly            122
automatic           120
pricePKR              5
dtype: int64

In [4]:
df.fueltype.value_counts()

Petrol                        383
PetrolCompressedNaturalGas     13
PetrolElectric                  6
Diesel                          1
Name: fueltype, dtype: int64

In [5]:
df.dtypes

title                object
make                 object
model                object
trim                 object
year                  int64
mileagekm            object
location             object
fueltype             object
registeredcity       object
color                object
enginecapacitycc    float64
assembly             object
automatic            object
pricePKR            float64
dtype: object

In [7]:
df['mileagekm'] = df['mileagekm'].str.replace(',', '')

In [8]:
df["mileagekm"] = df["mileagekm"].apply(pd.to_numeric)

In [12]:
df["enginecapacitycc"] = df["enginecapacitycc"].apply(pd.to_numeric)
df["pricePKR"] = df["pricePKR"].apply(pd.to_numeric)

In [14]:
df.dtypes

title                object
make                 object
model                object
trim                 object
year                  int64
mileagekm             int64
location             object
fueltype             object
registeredcity       object
color                object
enginecapacitycc    float64
assembly             object
automatic            object
pricePKR            float64
dtype: object

In [15]:
df.enginecapacitycc.fillna(df['enginecapacitycc'].mean(),inplace=True)

In [19]:
df.pricePKR.fillna(df['pricePKR'].mean(),inplace=True)

In [20]:
df.isna().sum()

title                 0
make                  0
model                 0
trim                  0
year                  0
mileagekm             0
location            252
fueltype             48
registeredcity        0
color                 4
enginecapacitycc      0
assembly            122
automatic           120
pricePKR              0
dtype: int64

In [21]:
df.fueltype.fillna('CompressedNaturalGas',inplace=True)

In [23]:
df.fueltype.value_counts()

Petrol                        383
CompressedNaturalGas           48
PetrolCompressedNaturalGas     13
PetrolElectric                  6
Diesel                          1
Name: fueltype, dtype: int64

In [24]:
df.fillna({
        'location': 'unknownLocation',
        'color': 'unknownColor',
        'assembly': 'unknownAssembly',
        'automatic': 'unknown',
        
    }, inplace= True)

In [25]:
df.isna().sum()

title               0
make                0
model               0
trim                0
year                0
mileagekm           0
location            0
fueltype            0
registeredcity      0
color               0
enginecapacitycc    0
assembly            0
automatic           0
pricePKR            0
dtype: int64

After Deleting some irrelevent coloumns
df.drop('column_name', axis=1, inplace=True)

In [29]:
df

,title,make,model,year,mileagekm,location,fueltype,registeredcity,color,enginecapacitycc,assembly,automatic,pricePKR
0,Toyota Corolla SE Saloon Automatic 2004,Toyota,Corolla,2004,186000,Husaini chowk Ranger market hasil pur road,Petrol,Karachi,White,1600.000000,local,Automatic,120000.0
1,Toyota Corolla Altis Grande CVT-i 1.8 2016,Toyota,Corolla,2016,159000,unknownLocation,Petrol,Punjab,White,1800.000000,local,Automatic,310000.0
2,Toyota Raize 2021,Toyota,Raize,2021,1700,189-B PakArab Society Ferozpur Road15-A Moulan...,Petrol,Un-Registered,Red,1000.000000,Imported,Automatic,439500.0
3,Honda Civic VTi Oriel 1.6 2004,Honda,Civic,2004,285000,unknownLocation,Petrol,Sialkot,Grey,1600.000000,local,unknown,137500.0
4,Toyota Vitz F 1.0 2018,Toyota,Vitz,2018,38000,Hockey Stadium Near Gourmet Bakery,Petrol,Lahore,White,1000.000000,local,Automatic,275000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
446,Mercedes Benz E-Class 1.8 E200 Kompressor 2003,Mercedes Benz,E-Class,2003,195478,"Ali Trade Centre, MM Alam Road, Block B1 Block...",Petrol,Lahore,Black,1439.141274,unknownAssembly,automatic,2500000.0
447,Toyota Corolla 1.3 XLI 2015,Toyota,Corolla,2015,1456,"Shop No 1, 2 Sawera Residency Ground floor Plo...",Petrol,Karachi,Black,1439.141274,unknownAssembly,manual,2120000.0
448,Hyundai Santro 1.0 Club GV 2006,Hyundai,Santro,2006,190110,"Shop No 1, 2 Sawera Residency Ground floor Plo...",PetrolCompressedNaturalGas,Karachi,White,1439.141274,unknownAssembly,manual,780000.0
449,Toyota Corolla 1.3 GLI 2002,Toyota,Corolla,2002,178861,"Plot, gate # 1, old bulb factory, near hamza q...",Petrol,Karachi,Green,1439.141274,unknownAssembly,manual,1350000.0
450,Honda Civic 1.8 i-VTEC Oriel CVT UG - FaceLift...,Honda,Civic,2019,84956,"Shop No 1, 2 Sawera Residency Ground floor Plo...",Petrol,Karachi,Black,1439.141274,unknownAssembly,automatic,3950000.0

In [35]:
df['VXR'] = df['title'].apply(lambda x: 1 if 'VXR' in x.upper() else 0)

In [36]:
df.VXR.value_counts()

0    402
1     49
Name: VXR, dtype: int64

In [37]:
df

,title,make,model,year,mileagekm,location,fueltype,registeredcity,color,enginecapacitycc,assembly,automatic,pricePKR,VXR
0,Toyota Corolla SE Saloon Automatic 2004,Toyota,Corolla,2004,186000,Husaini chowk Ranger market hasil pur road,Petrol,Karachi,White,1600.000000,local,Automatic,120000.0,0
1,Toyota Corolla Altis Grande CVT-i 1.8 2016,Toyota,Corolla,2016,159000,unknownLocation,Petrol,Punjab,White,1800.000000,local,Automatic,310000.0,0
2,Toyota Raize 2021,Toyota,Raize,2021,1700,189-B PakArab Society Ferozpur Road15-A Moulan...,Petrol,Un-Registered,Red,1000.000000,Imported,Automatic,439500.0,0
3,Honda Civic VTi Oriel 1.6 2004,Honda,Civic,2004,285000,unknownLocation,Petrol,Sialkot,Grey,1600.000000,local,unknown,137500.0,0
4,Toyota Vitz F 1.0 2018,Toyota,Vitz,2018,38000,Hockey Stadium Near Gourmet Bakery,Petrol,Lahore,White,1000.000000,local,Automatic,275000.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446,Mercedes Benz E-Class 1.8 E200 Kompressor 2003,Mercedes Benz,E-Class,2003,195478,"Ali Trade Centre, MM Alam Road, Block B1 Block...",Petrol,Lahore,Black,1439.141274,unknownAssembly,automatic,2500000.0,0
447,Toyota Corolla 1.3 XLI 2015,Toyota,Corolla,2015,1456,"Shop No 1, 2 Sawera Residency Ground floor Plo...",Petrol,Karachi,Black,1439.141274,unknownAssembly,manual,2120000.0,0
448,Hyundai Santro 1.0 Club GV 2006,Hyundai,Santro,2006,190110,"Shop No 1, 2 Sawera Residency Ground floor Plo...",PetrolCompressedNaturalGas,Karachi,White,1439.141274,unknownAssembly,manual,780000.0,0
449,Toyota Corolla 1.3 GLI 2002,Toyota,Corolla,2002,178861,"Plot, gate # 1, old bulb factory, near hamza q...",Petrol,Karachi,Green,1439.141274,unknownAssembly,manual,1350000.0,0
450,Honda Civic 1.8 i-VTEC Oriel CVT UG - FaceLift...,Honda,Civic,2019,84956,"Shop No 1, 2 Sawera Residency Ground floor Plo...",Petrol,Karachi,Black,1439.141274,unknownAssembly,automatic,3950000.0,0

In [40]:
df.loc[14]

title               Suzuki Mehran VXR (CNG) 2010
make                                      Suzuki
model                                     Mehran
year                                        2010
mileagekm                                 120000
location                         unknownLocation
fueltype                                  Petrol
registeredcity                         Islamabad
color                                     Silver
enginecapacitycc                           800.0
assembly                                   local
automatic                                unknown
pricePKR                                 67000.0
VXR                                            1
Name: 14, dtype: object

In [42]:
df['VXL'] = df['title'].apply(lambda x: 1 if 'VXL' in x.upper() else 0)
df.VXL.value_counts()

0    431
1     20
Name: VXL, dtype: int64

In [43]:
df.to_csv('data_cleaned.csv',index = False)